name: e_bike_tracking_app
description: A Flutter app for tracking and managing school e-bikes.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Navigation
  cupertino_icons: ^1.0.2
  
  # Maps
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  
  # Date and Time
  intl: ^0.18.1
  
  # State Management
  provider: ^6.1.1
  
  # Firebase (for future integration)
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_database: ^10.4.0
  
  # Charts (for activities screen)
  fl_chart: ^0.65.0
  
  # HTTP requests
  http: ^1.1.0
  
  # Local storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
